<!DOCTYPE HTML>
<html>
<head>
<title>
$title$
</title>
<link rel="stylesheet" type="text/css" href="/styleSIMAIBallot.css" />
</head>

<body>



<div id="page">
  <table width="100%">
    <tr>
      <td>
        <div class="title">
 			$title$
        </div>
      </td>
      <td>
        <img style="width: 300px;" src="/logo_simai.jpg"/>
      </td>
    </tr>
  </table>


<div class="risposta">
Il tuo voto 
<div style="padding: 2em; font-size: 140%;">$voto$</div>
e' stato registrato correttamente.
</div>


<div class="postamble">
La procedura di voto e' terminata. Grazie per aver votato, adesso e' possibile chiudere questa finestra.
</div>

</body>
</html>

